name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.19]
    name: ${{ matrix.os }} @ Go ${ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.os }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
